{"uuid": "ccf24ac6-d8ab-4a8e-8168-148cc97b509b", "children": ["83e694bc-3ac2-433c-a249-43c0dae1cb74"], "befores": [{"name": "init_driver", "status": "passed", "start": 1657720309074, "stop": 1657720338981}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/svc/PycharmProjects/SeleniumPythonProject/Framework/tests/conftest.py\", line 45, in init_driver\n    if request.node.rep_call.failed:\n"}, "start": 1657720369246, "stop": 1657720369247}], "start": 1657720309074, "stop": 1657720369247}