{"uuid": "e894fb00-54aa-4b8d-af0a-592e18d7da7c", "children": ["7b33ffca-b172-4b88-8b58-ff17ec943938", "ab5a35b1-bc7a-4f76-ab6f-ffb5223dd2a4"], "befores": [{"name": "init_driver", "status": "passed", "start": 1657720266989, "stop": 1657720302479}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/svc/PycharmProjects/SeleniumPythonProject/Framework/tests/conftest.py\", line 45, in init_driver\n    if request.node.rep_call.failed:\n"}, "start": 1657720327799, "stop": 1657720327802}], "start": 1657720266989, "stop": 1657720327802}