{"uuid": "8b1c0a56-dfdd-4a0c-a787-ce8632f0ebec", "children": ["540869d4-2950-473d-a31e-fb1d40a5cd36", "fd637967-d322-46e7-93f7-baf4cf8b30b7"], "befores": [{"name": "init_driver", "status": "passed", "start": 1657719633877, "stop": 1657719645603}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/svc/PycharmProjects/SeleniumPythonProject/Framework/tests/conftest.py\", line 41, in init_driver\n    if request.node.rep_call.failed:\n"}, "start": 1657719651642, "stop": 1657719651643}], "start": 1657719633877, "stop": 1657719651643}