{"uuid": "7424af26-1f39-4a5f-8e54-7282f9a875c1", "children": ["187c1ecd-0a52-465c-b7b0-d03d5c3ac373", "a23e4f91-17a7-4eb2-8c8a-97f9108e90bf"], "befores": [{"name": "init_driver", "status": "passed", "start": 1657720266990, "stop": 1657720284425}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/svc/PycharmProjects/SeleniumPythonProject/Framework/tests/conftest.py\", line 45, in init_driver\n    if request.node.rep_call.failed:\n"}, "start": 1657720307270, "stop": 1657720307271}], "start": 1657720266990, "stop": 1657720307271}