{"uuid": "20701706-d067-45bb-8236-93acbb890af8", "children": ["1227b350-7c62-48a2-a75e-b66aa0ccbf0d", "ed42d167-7b10-4cba-910a-a0813a97f120"], "befores": [{"name": "init_driver", "status": "passed", "start": 1657720651857, "stop": 1657720687109}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/svc/PycharmProjects/SeleniumPythonProject/Framework/tests/conftest.py\", line 45, in init_driver\n    if request.node.rep_call.failed:\n"}, "start": 1657720703924, "stop": 1657720703929}], "start": 1657720651857, "stop": 1657720703929}