{"uuid": "de0bd050-4f6b-4ccc-a143-2efa46849952", "children": ["9ef851be-bd8c-4f74-aa06-20bfeb4b9dd5", "882fab3b-b62b-4bd6-a728-179e4e06ebf8"], "befores": [{"name": "init_driver", "status": "passed", "start": 1657720694115, "stop": 1657720723222}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/svc/PycharmProjects/SeleniumPythonProject/Framework/tests/conftest.py\", line 45, in init_driver\n    if request.node.rep_call.failed:\n"}, "start": 1657720725306, "stop": 1657720725307}], "start": 1657720694115, "stop": 1657720725307}