{"uuid": "927c2ad2-27fa-4d89-b2ce-7a2211cd57e7", "children": ["648d2cc2-fa36-4493-b6a1-c0198b2d0935", "422e8f4c-96e2-48cc-bdfd-7f6d50947838"], "befores": [{"name": "init_driver", "status": "passed", "start": 1657719658229, "stop": 1657719665012}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/svc/PycharmProjects/SeleniumPythonProject/Framework/tests/conftest.py\", line 41, in init_driver\n    if request.node.rep_call.failed:\n"}, "start": 1657719667615, "stop": 1657719667615}], "start": 1657719658229, "stop": 1657719667615}