{"uuid": "e96d5da1-9f17-45a4-8488-7f446dbad7ac", "children": ["1b9da6af-51dd-4920-8858-eec380696c4b", "88b9b534-ac28-4a35-96f9-3f9bd362782b", "c483cd33-4a6d-42d0-acaf-daa46a3c9656", "fea682f8-925e-499b-b95c-68739513518d", "350b1398-c3e9-4c17-b4e5-011a962c9fef", "937e8e44-ca1c-493e-b51b-a1e3c5ae1741"], "befores": [{"name": "init_driver", "status": "passed", "start": 1657719633879, "stop": 1657719641228}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/svc/PycharmProjects/SeleniumPythonProject/Framework/tests/conftest.py\", line 41, in init_driver\n    if request.node.rep_call.failed:\n"}, "start": 1657719649544, "stop": 1657719649574}], "start": 1657719633879, "stop": 1657719649574}