{"uuid": "e7a25aa0-7616-41ad-9656-fae189c71b5f", "children": ["9b55eaa5-5075-407c-aa56-916cc68798d1", "32a5940a-23c8-4d0a-a353-8b520fdd23b6"], "befores": [{"name": "init_driver", "status": "passed", "start": 1657720684785, "stop": 1657720692080}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/svc/PycharmProjects/SeleniumPythonProject/Framework/tests/conftest.py\", line 45, in init_driver\n    if request.node.rep_call.failed:\n"}, "start": 1657720715891, "stop": 1657720715893}], "start": 1657720684785, "stop": 1657720715893}