{"uuid": "299483f0-94e0-4873-bd0b-cd53d9f33ff9", "children": ["820da365-575a-4969-964b-782db5f64d79", "62dc44b9-ce8e-4d5f-bfa7-55e5a7c9b496"], "befores": [{"name": "init_driver", "status": "passed", "start": 1657720266989, "stop": 1657720288122}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/svc/PycharmProjects/SeleniumPythonProject/Framework/tests/conftest.py\", line 45, in init_driver\n    if request.node.rep_call.failed:\n"}, "start": 1657720309402, "stop": 1657720309407}], "start": 1657720266989, "stop": 1657720309407}