{"uuid": "c9612345-b488-4be1-9339-e86a5cbf6283", "children": ["6e736e63-90b8-48d5-8357-cb9c9b7bb24f", "f6b56d43-fe17-402a-947b-d099b5412dea"], "befores": [{"name": "init_driver", "status": "passed", "start": 1657720651857, "stop": 1657720666683}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/svc/PycharmProjects/SeleniumPythonProject/Framework/tests/conftest.py\", line 45, in init_driver\n    if request.node.rep_call.failed:\n"}, "start": 1657720687802, "stop": 1657720687803}], "start": 1657720651857, "stop": 1657720687804}