{"uuid": "0a805fc0-d13c-4f0a-a6e6-ec39b989136c", "children": ["9ab9f988-9ea3-4963-93bc-d96a2a6f4120"], "befores": [{"name": "init_driver", "status": "passed", "start": 1657719650069, "stop": 1657719659910}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/svc/PycharmProjects/SeleniumPythonProject/Framework/tests/conftest.py\", line 41, in init_driver\n    if request.node.rep_call.failed:\n"}, "start": 1657719665699, "stop": 1657719665699}], "start": 1657719650069, "stop": 1657719665699}