{"uuid": "84d29865-d34d-4d87-b53c-1fbda928a66d", "children": ["d294ca9d-4d21-4d72-8e15-f9a1835a32ef", "a056ee66-1259-4540-93e6-9c3029a30221", "3090c567-96b5-4fc6-9329-5cfc7bf54650", "8925fdc3-fc7e-410e-9039-9dcfba369c89"], "befores": [{"name": "init_driver", "status": "passed", "start": 1657720307278, "stop": 1657720321906}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/svc/PycharmProjects/SeleniumPythonProject/Framework/tests/conftest.py\", line 45, in init_driver\n    if request.node.rep_call.failed:\n"}, "start": 1657720394285, "stop": 1657720394285}], "start": 1657720307278, "stop": 1657720394285}