{"uuid": "f396e494-c7c2-4eba-b15c-afad1196ffcb", "children": ["87bfdfb5-5628-41dc-98e5-5c649b8c78cd", "992fe2c9-dbd5-4513-8abb-317ffd0f8bd4"], "befores": [{"name": "init_driver", "status": "passed", "start": 1657720651857, "stop": 1657720674656}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/svc/PycharmProjects/SeleniumPythonProject/Framework/tests/conftest.py\", line 45, in init_driver\n    if request.node.rep_call.failed:\n"}, "start": 1657720694085, "stop": 1657720694086}], "start": 1657720651857, "stop": 1657720694086}