{"uuid": "c9b17813-2591-4407-ba4b-5c3a2ea1ef48", "children": ["ed59fbf1-a21c-4280-9e66-9f35339a1042", "296ef14c-0247-42c0-9d79-e073786853cb"], "befores": [{"name": "init_driver", "status": "passed", "start": 1657720651858, "stop": 1657720669207}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/svc/PycharmProjects/SeleniumPythonProject/Framework/tests/conftest.py\", line 45, in init_driver\n    if request.node.rep_call.failed:\n"}, "start": 1657720689195, "stop": 1657720689198}], "start": 1657720651858, "stop": 1657720689198}