{"uuid": "5ed3c8ae-74ee-4c7c-87c4-f9f82d73822d", "children": ["e2dcc6c7-2b46-449c-ad71-c72a03ffd0c9"], "befores": [{"name": "init_driver", "status": "passed", "start": 1657720369313, "stop": 1657720383530}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/svc/PycharmProjects/SeleniumPythonProject/Framework/tests/conftest.py\", line 45, in init_driver\n    if request.node.rep_call.failed:\n"}, "start": 1657720385832, "stop": 1657720385833}], "start": 1657720369313, "stop": 1657720385833}